### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by AI-student-wl** [haosulab/ActiveZero#1]
Hello, thank you for your excellent work. I want to reproduce this work, and I want to know some details of your data set production and the placement of data files: RGB, Depth, 2 * IR image, sensor internal parameters. Whether sensor pose is required, it is a 4 * 4 matrix consisting of rotation matrix R and translation matrix T. I use d435i to make data sets. Thank you for your help

**Comment by Isabella98Liu** [comment]
Hi, thanks for your question. The sensor pose is required and yes, it's a 4*4 pose matrix. In this project we use Intel RealSense D415 to build the real dataset. 

The simulation data files contain: 2 * IR images w/ infrared patterns, 2 * IR images w/o infrared patterns, 2 * depth images, camera meta files. 

The real data files contain: 2 * IR images w/ infrared patterns for different infrared pattern strength (we use 6 different IR intensities, so in total 2*6=12 * IR images), 2 * depth images, camera meta files.

**Comment by AI-student-wl** [comment]
How do I collect the left and right infrared images with different intensities? I have only one intensity here. If it is code acquisition, can I see your acquisition code? Thank you for your help

**Comment by AI-student-wl** [comment]
img_real_L, img_real_L_no_ir， What is the difference between the two data?

**Comment by AI-student-wl** [comment]
In the messytable.py file, img_ disp_ L and img_ real_ L_ temporal_ What does ir mean?

**Comment by Toseethebiggerworld** [comment]
> In the messytable.py file, img_ disp_ L and img_ real_ L_ temporal_ What does ir mean?

Have you obtained the paper dataset, or successfully created by yourself?
